### ISSUE TITLE
why R

### ISSUE THREAD

**Issue by caxieyou** [mikialex/rendiation#96]
YCoCgRColor why there is a R?

https://github.com/mikialex/rendiation/blob/fb1b83ee6031648c4e8b1733594923b60f51a5dd/components/color/src/ycocg.rs#L6

**Comment by mikialex** [comment]
It's for YCoCg-R variation. See <https://en.wikipedia.org/wiki/YCoCg>

**Comment by caxieyou** [comment]
cool
thx
