### ISSUE TITLE
correct by case wrong

### ISSUE THREAD

**Issue by caxieyou** [mikialex/rendiation#99]
https://github.com/mikialex/rendiation/blob/4e8dd161a0540968703c2d5eaf0cd364ecbe65b0/components/texture/core/src/address.rs#L34

should not be all ClampToEdge.

**Comment by mikialex** [comment]
fixed in [b665af6](https://github.com/mikialex/rendiation/commit/b665af6b3ef8e954895632cbfd0e8ef608bb1251)
